services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:80"
    env_file:
      - api/.env.DOCKER

  client-ts:
    build:
      context: ./client-ts
      dockerfile: Dockerfile
    container_name: client-ts
    env_file:
      - client-ts/.env.DOCKER
    depends_on:
      - api
