services:
  blockchain:
    container_name: blockchain
    hostname: blockchain
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - "./blockchain/clef:/mount/clef"
      - "./blockchain/keystore:/mount/keystore"
      - "./blockchain/datadir:/mount/datadir"
    env_file:
      - ./blockchain/.env
    networks:
      blockchain-network:
        aliases:
          - blockchain

  api:
    container_name: api
    hostname: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    env_file:
      - ./api/.env.DOCKER
    depends_on:
      - blockchain
    networks:
      blockchain-network:
      api-network:
        aliases:
          - api

  client-ts:
    build:
      context: ./client-ts
      dockerfile: Dockerfile
    container_name: client-ts
    env_file:
      - ./client-ts/.env.DOCKER
    depends_on:
      - api
    networks:
      - api-network

networks:
  blockchain-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.254.0/28
  api-network:
